version: '3.8'

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: wallet_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/wallet_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
volumes:
  postgres-data: