spring:
  application:
    name: task

  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5433/wallet_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.xml
